### ISSUE TITLE
Leak Detection - New Water Map Service

### ISSUE THREAD

**Issue by JMurk** [JMurk/Leak_Detection_Issues#57] opened 2014-04-18 19:28 UTC
A new Map service has been created on GW03 for use in the leak detection application.  Please use Leak_Detection_App_Water_Features in place of 1108_Waterdev.

**Comment by alanfoster99** [comment] 2014-04-21 15:03
Additionally, please make sure the report is also using this service for its live map instance.

**Comment by kanglu666** [comment] 2014-04-21 15:11
done

**Comment by tarheelgis** [comment] 2014-04-22 14:08
Just saw the note about the report for this one will post a change shortly

**Comment by kanglu666** [comment] 2014-04-22 16:37
done

**Comment by alanfoster99** [comment] 2014-04-22 17:37
Can't tell a difference in the report -- is this due to the scale of the map in the report?

**Comment by kanglu666** [comment] 2014-04-22 17:41
assign this to Eric. he needs to update the mapservice for the report

**Comment by tarheelgis** [comment] 2014-04-22 18:21
Added please test

**Comment by alanfoster99** [comment] 2014-04-22 19:49
Confirmed and closed.

**Closed as completed by alanfoster99** 2014-04-22 19:49 UTC
Labels: design
